/*======
This file is part of Percona Server for MongoDB.

Copyright (C) 2024-present Percona and/or its affiliates. All rights reserved.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the Server Side Public License, version 1,
    as published by MongoDB, Inc.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    Server Side Public License for more details.

    You should have received a copy of the Server Side Public License
    along with this program. If not, see
    <http://www.mongodb.com/licensing/server-side-public-license>.

    As a special exception, the copyright holders give permission to link the
    code of portions of this program with the OpenSSL library under certain
    conditions as described in each individual source file and distribute
    linked combinations including the program with the OpenSSL library. You
    must comply with the Server Side Public License in all respects for
    all of the code used other than as permitted herein. If you modify file(s)
    with this exception, you may extend this exception to your version of the
    file(s), but you are not obligated to do so. If you do not wish to do so,
    delete this exception statement from your version. If you delete this
    exception statement from all source files in the program, then also delete
    it in the license file.
======= */


#include <memory>
#include <utility>

#include "mongo/base/init.h"
#include "mongo/bson/bsonobj.h"
#include "mongo/db/catalog/collection_catalog.h"
#include "mongo/db/catalog_raii.h"
#include "mongo/db/concurrency/d_concurrency.h"
#include "mongo/db/concurrency/exception_util.h"
#include "mongo/db/db_raii.h"
#include "mongo/db/namespace_string.h"
#include "mongo/db/op_observer/op_observer.h"
#include "mongo/db/operation_context.h"
#include "mongo/db/repl/oplog.h"
#include "mongo/db/storage/durable_catalog.h"
#include "mongo/db/storage/wiredtiger/wiredtiger_import.h"
#include "mongo/logv2/log.h"
#include "mongo/util/uuid.h"

#define MONGO_LOGV2_DEFAULT_COMPONENT ::mongo::logv2::LogComponent::kReplication


namespace mongo {
namespace repl {
namespace {

void applyImportCollection(OperationContext* opCtx,
                           const UUID& importUUID,
                           const NamespaceString& nss,
                           long long numRecords,
                           long long dataSize,
                           const BSONObj& catalogEntry,
                           const BSONObj& storageMetadata,
                           bool isDryRun,
                           OplogApplication::Mode mode) {
    // Import the collection and its indexes.
    writeConflictRetry(opCtx, "applyImportCollection", nss.ns(), [&] {
        LOGV2_DEBUG(29118, 1, "Attaching collection", "ns"_attr = nss);
        AutoGetDb autoDb(opCtx, nss.dbName(), MODE_IX);
        auto* db = autoDb.ensureDbExists(opCtx);
        invariant(db);
        const Lock::CollectionLock collLock(opCtx, nss, MODE_X);
        auto catalog = CollectionCatalog::get(opCtx);
        WriteUnitOfWork wunit(opCtx);
        const AutoStatsTracker statsTracker(opCtx,
                                            nss,
                                            Top::LockType::NotLocked,
                                            AutoStatsTracker::LogMode::kUpdateTopAndCurOp,
                                            catalog->getDatabaseProfileLevel(nss.dbName()));

        // If the collection creation rolls back, ensure that the Top entry created for the
        // collection is deleted.
        opCtx->recoveryUnit()->onRollback(
            [nss, serviceContext = opCtx->getServiceContext()](OperationContext*) {
                Top::get(serviceContext).collectionDropped(nss);
            });

        // Create Collection object.
        auto* storageEngine = opCtx->getServiceContext()->getStorageEngine();
        auto* durableCatalog = storageEngine->getCatalog();
        ImportOptions importOptions(ImportOptions::ImportCollectionUUIDOption::kKeepOld);
        importOptions.importTimestampRule = ImportOptions::ImportTimestampRule::kStable;
        // Since we are using the ident id generated by this recipient node, ident collisions in
        // the future after import is not possible. So, it's ok to skip the ident collision
        // check. Otherwise, we would unnecessarily generate new rand after each collection
        // import.
        importOptions.skipIdentCollisionCheck = true;

        auto importResult = uassertStatusOK(durableCatalog->importCollection(
            opCtx, nss, catalogEntry, storageMetadata, importOptions));

        const auto md = durableCatalog->getMetaData(opCtx, importResult.catalogId);
        for (const auto& index : md->indexes) {
            uassert(6114301, "Cannot import non-ready indexes", index.ready);
        }

        std::shared_ptr<Collection> ownedCollection = Collection::Factory::get(opCtx)->make(
            opCtx, nss, importResult.catalogId, md, std::move(importResult.rs));
        ownedCollection->init(opCtx);
        ownedCollection->setCommitted(false);

        // Update the number of records and data size on commit.
        opCtx->recoveryUnit()->registerChange(
            makeCountsChange(ownedCollection->getRecordStore(), numRecords, dataSize));

        CollectionCatalog::get(opCtx)->onCreateCollection(opCtx, std::move(ownedCollection));

        auto importedCatalogEntry = durableCatalog->getCatalogEntry(opCtx, importResult.catalogId);
        opCtx->getServiceContext()->getOpObserver()->onImportCollection(opCtx,
                                                                        importUUID,
                                                                        nss,
                                                                        numRecords,
                                                                        dataSize,
                                                                        importedCatalogEntry,
                                                                        storageMetadata,
                                                                        false);

        wunit.commit();

        // TODO: remove if not necessary
        // if (numRecords > 0) {
        //     cluster_parameters::maybeUpdateClusterParametersPostImportCollectionCommit(opCtx,
        //     nss);
        // }

        LOGV2(29119,
              "Attached collection",
              "ns"_attr = nss,
              "numRecordsApprox"_attr = numRecords,
              "dataSizeApprox"_attr = dataSize);
    });
}

MONGO_INITIALIZER(RegisterApplyImportCollection)(InitializerContext* const) {
    registerApplyImportCollectionFn(&applyImportCollection);
}

}  // namespace
}  // namespace repl
}  // namespace mongo
