# -*- mode: python -*-
Import("env")

env = env.Clone()

env.Library(
    target='ldapmanagerbase',
    source=[
        'ldap_manager.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/service_context',
    ],
)

env.Library(
    target='ldapmanager',
    source=[
        'ldap_manager_impl.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        'ldapmanagerbase',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/ldap_options',
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/util/background_job',
    ],
    SYSLIBDEPS=[
        'ldap',
        'lber',
    ],
)
